import type { Metadata } from "next";
import Link from "next/link";
import { phone } from "../components/site-data";

export const metadata: Metadata = {
  title: "Cancellation and Refund Policy",
  description: "Cancellation, return and refund information for Persevex meat, fruits, vegetables, cocopeat and coir fiber orders.",
};

export default function CancellationAndRefundPolicy() {
  return <section className="section legal-page inner-page"><div className="wrap legal-wrap">
    <span className="section-kicker">PERSEVEX</span><h1>Cancellation and Refund Policy</h1>
    <p className="legal-updated">Last updated: 4 October 2026</p>
    <p>This policy applies to orders for chicken, mutton, other meat cuts, fruits, vegetables, cocopeat and coir fiber placed with Persevex. Please read it alongside our <Link href="/terms-and-conditions">Terms and Conditions</Link> and the written details confirmed for your order. Nothing in this policy limits your rights under applicable Indian consumer protection law.</p>
    <section><h2>1. Enquiries and confirmed orders</h2><p>Adding products to your cart or saving an enquiry does not confirm an order or take payment. You may change or withdraw an unconfirmed enquiry without a cancellation charge. An order is confirmed when you and Persevex agree its products, quantities, price, payment and delivery arrangements.</p></section>
    <section><h2>2. Cancelling or changing an order</h2><p>Call <a href={`tel:${phone}`}>{phone}</a> as soon as possible, quoting your order reference and the items you wish to cancel or change. Please ask our team to confirm the outcome; sending a request alone does not confirm cancellation.</p><p>If preparation, custom cutting, packing or dispatch has not started, we will cancel the requested items and refund any amount paid for them. Once these activities have started, changes or cancellations for personal preference may be limited, especially for perishable goods or meat prepared to your instructions. Any applicable restriction or charge must be disclosed and agreed before order confirmation and must comply with applicable law. No undisclosed cancellation fee will be imposed.</p></section>
    <section><h2>3. Orders we cannot fulfil</h2><p>If an item is unavailable or we cannot fulfil the agreed order, we will contact you. You may accept a revised order or cancel the affected items and receive a refund of any payment made for them. We will not substitute a different meat type, cut or product without your agreement.</p></section>
    <section><h2>4. Meat, fruits and vegetables</h2><p>Because these products are perishable and require appropriate handling, we do not accept change-of-mind returns after delivery. This restriction does not apply to goods that arrive spoiled, unsafe, damaged, incorrect, materially different from the agreed description, or short in quantity, or to other remedies required by law.</p><p>Check your delivery as soon as practical. If there is a problem, contact us promptly, preferably on the day of delivery, with your order reference, a description and any available photographs of the goods, packaging and labels. Prompt reporting helps us assess perishable goods; a later report does not automatically remove your statutory rights. An unboxing video is not required.</p><p>Do not consume goods you suspect are unsafe. Keep them separate and follow the storage instructions where safe to do so. Contact us for collection or disposal instructions; do not send perishable products back without arrangements. We will not require you to keep or transport unsafe food.</p></section>
    <section><h2>5. Cocopeat and coir fiber</h2><p>Please check the delivered product, weight, packing and agreed specifications. Contact us promptly if goods are damaged, incorrect, short in quantity or do not meet the confirmed specifications. Keep packaging and supporting information where practical. Change-of-mind returns for correctly supplied goods require prior agreement; any conditions and costs must be confirmed before you send goods back.</p></section>
    <section><h2>6. Resolving delivery and product issues</h2><p>For a confirmed problem attributable to the goods or our fulfilment, we will provide the appropriate refund, replacement or correction in accordance with your applicable rights. A replacement will be arranged with your agreement and subject to availability; you will not be required to accept store credit instead of a refund you are entitled to. For missing quantities or issues affecting only part of an order, the remedy will cover the affected items or quantity unless a wider remedy is required.</p><p>Report non-delivery or delivery beyond the agreed schedule so we can investigate and provide the remedy required by law. We will cover reasonable collection or replacement delivery costs for confirmed incorrect or defective goods. Ordinary variation in appearance does not by itself establish a defect, but goods must meet the description, quantity and specifications agreed for your order.</p></section>
    <section><h2>7. Refund method and timing</h2><p>Refunds cover the eligible amount actually paid. We will confirm the amount and expected processing date when the refund is agreed and process it without undue delay within any applicable legal deadline. Refunds will normally use the original payment method; for cash or where that method cannot receive a refund, we will agree a suitable alternative with you. Bank or payment-provider processing can affect when the funds appear in your account.</p><p>Keep your order reference and payment receipt until the refund is complete. We will never ask for your OTP, card PIN or UPI PIN to issue a refund.</p></section>
    <section><h2>8. Contact and unresolved concerns</h2><p>For cancellations, delivery concerns or refund requests, call <a href={`tel:${phone}`}>{phone}</a>. Provide your order reference, contact number, affected products and payment details relevant to the request. If a concern remains unresolved, ask our team to review it. This policy does not restrict access to consumer grievance channels or other remedies available under law.</p></section>
  </div></section>;
}
