export type Product = {
  id: string;
  unit: string;
  kind?: string;
  image?: string;
  imageLabel: string;
  category: string;
  name: string;
  description: string;
  price: number;
  paymentUrl: string;
  razorpayPageId: string;
  enquiry: string;
};

export const products: Product[] = [
  {
    id: "meat-cuts",
    price: 650,
    unit: "kg",
    image: "/meat-veg-prod/meat1.webp",
    imageLabel: "Large meat cuts displayed with assorted vegetables",
    category: "01 / MEAT",
    name: "Meat Cuts",
    paymentUrl: "https://rzp.io/rzp/meat-cuts-EAT650",
    razorpayPageId: "pl_TkW8ZKYEbXQHUx",
    description: "Enquire about meat cuts for your kitchen, catering or business needs. Share your preferred cut, quantity and delivery location for availability and a quote.",
    enquiry: "Enquire about meat cuts →",
  },
  {
    id: "mixed-meat",
    price: 500,
    unit: "kg",
    image: "/meat-veg-prod/meat2.jpeg",
    imageLabel: "Assortment of chicken portions, red meat, sausages and sliced meat",
    category: "02 / MEAT",
    name: "Chicken",
    paymentUrl: "https://rzp.io/rzp/chicken-EAT500",
    razorpayPageId: "pl_TkWAWdAXEttfHG",
    description: "Chicken for everyday meals, catering and business kitchens. Share your preferred cuts and quantity to check availability.",
    enquiry: "Enquire about chicken →",
  },
  {
    id: "mutton",
    price: 1000,
    unit: "kg",
    image: "/meat-veg-prod/mutton.jpeg",
    imageLabel: "Mutton cuts",
    category: "03 / MEAT",
    name: "Mutton",
    paymentUrl: "https://rzp.io/rzp/mutton-EAT1000",
    razorpayPageId: "pl_TkWCiHeCu2QPx8",
    description: "Mutton for curries, biryanis and other kitchen favourites. Share your preferred cuts and quantity to check availability.",
    enquiry: "Enquire about mutton →",
  },
  {
    id: "apples",
    price: 180,
    unit: "kg",
    image: "/meat-veg-prod/apples.webp",
    imageLabel: "Red apples packed in a produce box",
    category: "04 / FRUITS",
    name: "Apples",
    paymentUrl: "https://rzp.io/rzp/apples-EAT180",
    razorpayPageId: "pl_TkWDVZ9RZuS5ak",
    description: "Crisp apples for fruit bowls, baking and everyday snacking.",
    enquiry: "Enquire about apples →",
  },
  {
    id: "strawberries",
    price: 280,
    unit: "kg",
    image: "/meat-veg-prod/strawberry.jpeg",
    imageLabel: "Red strawberries among leaves and white flowers",
    category: "05 / FRUITS",
    name: "Strawberries",
    paymentUrl: "https://rzp.io/rzp/strawberries-EAT280",
    razorpayPageId: "pl_TkWE66UNpGiTVJ",
    description: "Strawberries for fresh servings, desserts, smoothies and preserves.",
    enquiry: "Enquire about strawberries →",
  },
  {
    id: "ice-apples",
    price: 120,
    unit: "kg",
    image: "/meat-veg-prod/iceapple.jpeg",
    imageLabel: "Whole palmyra fruits and opened shells",
    category: "06 / FRUITS",
    name: "Ice Apples",
    paymentUrl: "https://rzp.io/rzp/ice-apples-EAT120",
    razorpayPageId: "pl_TkWEZcb5CEY4SY",
    description: "Palmyra fruit for seasonal fruit servings and refreshing desserts.",
    enquiry: "Enquire about ice apples →",
  },
  {
    id: "oranges",
    price: 100,
    unit: "kg",
    image: "/meat-veg-prod/orange.webp",
    imageLabel: "Oranges growing on trees",
    category: "07 / FRUITS",
    name: "Oranges",
    paymentUrl: "https://rzp.io/rzp/oranges-EAT100",
    razorpayPageId: "pl_TkWFFRPjK8D5ci",
    description: "Oranges for fruit platters, juice and citrus desserts.",
    enquiry: "Enquire about oranges →",
  },
  {
    id: "pineapples",
    price: 70,
    unit: "kg",
    image: "/meat-veg-prod/pineapple.jpeg",
    imageLabel: "Whole ripe pineapples with leafy crowns",
    category: "08 / FRUITS",
    name: "Pineapples",
    paymentUrl: "https://rzp.io/rzp/pineapples-EAT70",
    razorpayPageId: "pl_TkWFpITAvFIITk",
    description: "Pineapples for fruit bowls, juices, desserts and grilled dishes.",
    enquiry: "Enquire about pineapples →",
  },
  {
    id: "passion-fruit",
    price: 250,
    unit: "kg",
    image: "/meat-veg-prod/longan.jpeg",
    imageLabel: "Purple-red passion fruits growing on a vine",
    category: "09 / FRUITS",
    name: "Passion Fruit",
    paymentUrl: "https://rzp.io/rzp/passion-fruit-EAT250",
    razorpayPageId: "pl_TkWGVgpw6OCmfu",
    description: "Passion fruit for tangy juices, sauces and desserts.",
    enquiry: "Enquire about passion fruit →",
  },
  {
    id: "pomegranates",
    price: 160,
    unit: "kg",
    image: "/meat-veg-prod/pomegranate.jpeg",
    imageLabel: "Pomegranates growing on trees",
    category: "10 / FRUITS",
    name: "Pomegranates",
    paymentUrl: "https://rzp.io/rzp/pomegranates-EAT160",
    razorpayPageId: "pl_TkWH7wksrZLEXW",
    description: "Pomegranates for fruit servings, salads, garnishes and juices.",
    enquiry: "Enquire about pomegranates →",
  },
  {
    id: "grapes",
    price: 120,
    unit: "kg",
    image: "/meat-veg-prod/grapes.jpeg",
    imageLabel: "Green, red and dark grapes in bunches",
    category: "11 / FRUITS",
    name: "Grapes",
    paymentUrl: "https://rzp.io/rzp/grapes-EAT120",
    razorpayPageId: "pl_TkWHmotQvcpwhN",
    description: "Grapes for snacking, fruit platters and fresh desserts.",
    enquiry: "Enquire about grapes →",
  },
  {
    id: "bananas",
    price: 60,
    unit: "kg",
    image: "/meat-veg-prod/banana.jpeg",
    imageLabel: "Bunches of green and yellow bananas",
    category: "12 / FRUITS",
    name: "Bananas",
    paymentUrl: "https://rzp.io/rzp/bananas-EAT60",
    razorpayPageId: "pl_TkWIQq5ywINfFh",
    description: "Bananas for everyday fruit servings, smoothies and baking.",
    enquiry: "Enquire about bananas →",
  },
  {
    id: "litchis",
    price: 220,
    unit: "kg",
    image: "/meat-veg-prod/litchi.jpeg",
    imageLabel: "Bunches of red litchis growing on trees",
    category: "13 / FRUITS",
    name: "Litchis",
    paymentUrl: "https://rzp.io/rzp/litchis-EAT220",
    razorpayPageId: "pl_TkWJ4GsX2KEmAX",
    description: "Litchis for seasonal fruit platters, desserts and drinks.",
    enquiry: "Enquire about litchis →",
  },
  {
    id: "papayas",
    price: 50,
    unit: "kg",
    image: "/meat-veg-prod/images (4).jpeg",
    imageLabel: "Green and ripening papayas growing on a tree",
    category: "14 / FRUITS",
    name: "Papayas",
    paymentUrl: "https://rzp.io/rzp/papayas-EAT50",
    razorpayPageId: "pl_TkWJeVfqEA1KV7",
    description: "Papayas for fruit bowls, smoothies and kitchen preparation.",
    enquiry: "Enquire about papayas →",
  },
  {
    id: "seasonal-vegetables",
    price: 60,
    unit: "kg",
    image: "/meat-veg-prod/veg1.jpg",
    imageLabel: "Market display of beans, carrots, cabbages and assorted vegetables",
    category: "15 / VEGETABLES",
    name: "Seasonal Vegetables",
    paymentUrl: "https://rzp.io/rzp/seasonal-vegetables-EAT60",
    razorpayPageId: "pl_TkWKAVDZq76mH4",
    description: "An assortment of vegetables for everyday cooking and larger kitchen requirements. Enquire about the current selection and quantities available.",
    enquiry: "Enquire about seasonal vegetables →",
  },
  {
    id: "green-vegetables",
    price: 80,
    unit: "kg",
    image: "/meat-veg-prod/veg2.jpeg",
    imageLabel: "Baskets of green vegetables, cabbages, aubergines and broccoli",
    category: "16 / GREEN VEGETABLES",
    name: "Green Vegetable Selection",
    paymentUrl: "https://rzp.io/rzp/green-vegetables-EAT80",
    razorpayPageId: "pl_TkWKnG6zufd0NM",
    description: "Explore a selection of green vegetables for your household or business. Share your preferred varieties and order size to check availability.",
    enquiry: "Enquire about green vegetables →",
  },
  {
    id: "mixed-vegetables",
    price: 90,
    unit: "kg",
    image: "/meat-veg-prod/veg3.jpeg",
    imageLabel: "Colourful assortment of leafy greens, peppers, corn, mushrooms and root vegetables",
    category: "17 / MIXED PRODUCE",
    name: "Mixed Vegetable Assortment",
    paymentUrl: "https://rzp.io/rzp/mixed-vegetables-EAT90",
    razorpayPageId: "pl_TkWLQJ5BJH0wLQ",
    description: "A varied vegetable selection to suit different recipes and menus. Send your produce list and quantities to discuss a custom assortment.",
    enquiry: "Enquire about mixed vegetables →",
  },
  {
    id: "potatoes",
    price: 40,
    unit: "kg",
    image: "/meat-veg-prod/potatoes.jpeg",
    imageLabel: "Assortment of whole potatoes",
    category: "18 / VEGETABLES",
    name: "Potatoes",
    paymentUrl: "https://rzp.io/rzp/potatoes-EAT40",
    razorpayPageId: "pl_TkWM2fFSixkcHw",
    description: "A kitchen staple for curries, roasting, mashing and frying.",
    enquiry: "Enquire about potatoes →",
  },
  {
    id: "red-chillies",
    price: 100,
    unit: "kg",
    image: "/meat-veg-prod/chillies.jpeg",
    imageLabel: "Fresh red chillies with green stems",
    category: "19 / VEGETABLES",
    name: "Red Chillies",
    paymentUrl: "https://rzp.io/rzp/red-chillies-EAT100",
    razorpayPageId: "pl_TkWMeOLBKF6XDs",
    description: "Red chillies for adding heat and colour to sauces, curries and marinades.",
    enquiry: "Enquire about red chillies →",
  },
  {
    id: "sweet-potatoes",
    price: 60,
    unit: "kg",
    image: "/meat-veg-prod/sweet-potato.jpeg",
    imageLabel: "Freshly harvested sweet potatoes in a crate",
    category: "20 / VEGETABLES",
    name: "Sweet Potatoes",
    paymentUrl: "https://rzp.io/rzp/sweet-potatoes-EAT60",
    razorpayPageId: "pl_TkWNDcvp7PFZ4g",
    description: "Sweet potatoes for roasting, steaming and sweet or savoury dishes.",
    enquiry: "Enquire about sweet potatoes →",
  },
  {
    id: "red-peppers",
    price: 140,
    unit: "kg",
    image: "/meat-veg-prod/capsicum.jpeg",
    imageLabel: "Glossy red peppers packed in a crate",
    category: "21 / VEGETABLES",
    name: "Red Peppers",
    paymentUrl: "https://rzp.io/rzp/red-peppers-EAT140",
    razorpayPageId: "pl_TkWNnG2gh9FrKt",
    description: "Red peppers for sauces, roasting and savoury kitchen recipes.",
    enquiry: "Enquire about red peppers →",
  },
  {
    id: "cocopeat",
    price: 300,
    unit: "kg",
    kind: "cocopeat",
    imageLabel: "Cured cocopeat",
    category: "22 / GROWING MEDIUM",
    name: "Cocopeat",
    paymentUrl: "https://rzp.io/rzp/cocopeat-EAT300",
    razorpayPageId: "pl_TkWOODYlnbAfWM",
    description: "A light coconut pith medium valued for moisture retention and root aeration. Suitable for nurseries, gardening and growing systems when prepared to the required specification.",
    enquiry: "Enquire about cocopeat →",
  },
  {
    id: "coir-fiber",
    price: 25,
    unit: "kg",
    kind: "fiber",
    imageLabel: "Coir fiber bales",
    category: "23 / NATURAL FIBER",
    name: "Coir Fiber",
    paymentUrl: "https://rzp.io/rzp/coir-fiber-EAT25",
    razorpayPageId: "pl_TkWP0kkGcd3Whh",
    description: "Strong natural fiber separated from coconut husks for industrial applications such as ropes, mats, padding and geotextiles.",
    enquiry: "Enquire about coir fiber →",
  },
];
