export type Product = {
  id: string;
  unit: string;
  kind?: string;
  image?: string;
  imageLabel: string;
  category: string;
  name: string;
  description: string;
  price: number;
  enquiry: string;
};

export const products: Product[] = [
  {
    id: "cocopeat",
    price: 300,
    unit: "25 kg bag",
    kind: "cocopeat",
    imageLabel: "Cured cocopeat",
    category: "01 / GROWING MEDIUM",
    name: "Cocopeat",
    description: "A light coconut pith medium valued for moisture retention and root aeration. Suitable for nurseries, gardening and growing systems when prepared to the required specification.",
    enquiry: "Enquire about cocopeat →",
  },
  {
    id: "coir-fiber",
    price: 25,
    unit: "kg",
    kind: "fiber",
    imageLabel: "Coir fiber bales",
    category: "02 / NATURAL FIBER",
    name: "Coir Fiber",
    description: "Strong natural fiber separated from coconut husks for industrial applications such as ropes, mats, padding and geotextiles.",
    enquiry: "Enquire about coir fiber →",
  },
  {
    id: "meat-cuts",
    price: 650,
    unit: "kg",
    image: "/meat-veg-prod/meat1.webp",
    imageLabel: "Large meat cuts displayed with assorted vegetables",
    category: "03 / MEAT",
    name: "Meat Cuts",
    description: "Enquire about meat cuts for your kitchen, catering or business needs. Share your preferred cut, quantity and delivery location for availability and a quote.",
    enquiry: "Enquire about meat cuts →",
  },
  {
    id: "mixed-meat",
    price: 450,
    unit: "kg",
    image: "/meat-veg-prod/meat2.jpeg",
    imageLabel: "Assortment of chicken portions, red meat, sausages and sliced meat",
    category: "04 / MEAT ASSORTMENTS",
    name: "Mixed Meat Selection",
    description: "A range of meat options for different menus and cooking requirements. Let us know the types and portions you need to discuss a suitable order.",
    enquiry: "Enquire about mixed meats →",
  },
  {
    id: "seasonal-vegetables",
    price: 60,
    unit: "kg",
    image: "/meat-veg-prod/veg1.jpg",
    imageLabel: "Market display of beans, carrots, cabbages and assorted vegetables",
    category: "05 / VEGETABLES",
    name: "Seasonal Vegetables",
    description: "An assortment of vegetables for everyday cooking and larger kitchen requirements. Enquire about the current selection and quantities available.",
    enquiry: "Enquire about seasonal vegetables →",
  },
  {
    id: "green-vegetables",
    price: 80,
    unit: "kg",
    image: "/meat-veg-prod/veg2.jpeg",
    imageLabel: "Baskets of green vegetables, cabbages, aubergines and broccoli",
    category: "06 / GREEN VEGETABLES",
    name: "Green Vegetable Selection",
    description: "Explore a selection of green vegetables for your household or business. Share your preferred varieties and order size to check availability.",
    enquiry: "Enquire about green vegetables →",
  },
  {
    id: "mixed-vegetables",
    price: 90,
    unit: "kg",
    image: "/meat-veg-prod/veg3.jpeg",
    imageLabel: "Colourful assortment of leafy greens, peppers, corn, mushrooms and root vegetables",
    category: "07 / MIXED PRODUCE",
    name: "Mixed Vegetable Assortment",
    description: "A varied vegetable selection to suit different recipes and menus. Send your produce list and quantities to discuss a custom assortment.",
    enquiry: "Enquire about mixed vegetables →",
  },
  {
    id: "apples",
    price: 180,
    unit: "kg",
    image: "/meat-veg-prod/apples.webp",
    imageLabel: "Red apples packed in a produce box",
    category: "08 / FRUITS",
    name: "Apples",
    description: "Crisp apples for fruit bowls, baking and everyday snacking.",
    enquiry: "Enquire about apples →",
  },
  {
    id: "potatoes",
    price: 40,
    unit: "kg",
    image: "/meat-veg-prod/potatoes.jpeg",
    imageLabel: "Assortment of whole potatoes",
    category: "09 / VEGETABLES",
    name: "Potatoes",
    description: "A kitchen staple for curries, roasting, mashing and frying.",
    enquiry: "Enquire about potatoes →",
  },
  {
    id: "strawberries",
    price: 280,
    unit: "kg",
    image: "/meat-veg-prod/strawberry.jpeg",
    imageLabel: "Red strawberries among leaves and white flowers",
    category: "10 / FRUITS",
    name: "Strawberries",
    description: "Strawberries for fresh servings, desserts, smoothies and preserves.",
    enquiry: "Enquire about strawberries →",
  },
  {
    id: "ice-apples",
    price: 120,
    unit: "kg",
    image: "/meat-veg-prod/iceapple.jpeg",
    imageLabel: "Whole palmyra fruits and opened shells",
    category: "11 / FRUITS",
    name: "Ice Apples",
    description: "Palmyra fruit for seasonal fruit servings and refreshing desserts.",
    enquiry: "Enquire about ice apples →",
  },
  {
    id: "red-chillies",
    price: 100,
    unit: "kg",
    image: "/meat-veg-prod/chillies.jpeg",
    imageLabel: "Fresh red chillies with green stems",
    category: "12 / VEGETABLES",
    name: "Red Chillies",
    description: "Red chillies for adding heat and colour to sauces, curries and marinades.",
    enquiry: "Enquire about red chillies →",
  },
  {
    id: "oranges",
    price: 100,
    unit: "kg",
    image: "/meat-veg-prod/orange.webp",
    imageLabel: "Oranges growing on trees",
    category: "13 / FRUITS",
    name: "Oranges",
    description: "Oranges for fruit platters, juice and citrus desserts.",
    enquiry: "Enquire about oranges →",
  },
  {
    id: "pineapples",
    price: 70,
    unit: "kg",
    image: "/meat-veg-prod/pineapple.jpeg",
    imageLabel: "Whole ripe pineapples with leafy crowns",
    category: "14 / FRUITS",
    name: "Pineapples",
    description: "Pineapples for fruit bowls, juices, desserts and grilled dishes.",
    enquiry: "Enquire about pineapples →",
  },
  {
    id: "sweet-potatoes",
    price: 60,
    unit: "kg",
    image: "/meat-veg-prod/sweet-potato.jpeg",
    imageLabel: "Freshly harvested sweet potatoes in a crate",
    category: "15 / VEGETABLES",
    name: "Sweet Potatoes",
    description: "Sweet potatoes for roasting, steaming and sweet or savoury dishes.",
    enquiry: "Enquire about sweet potatoes →",
  },
  {
    id: "passion-fruit",
    price: 250,
    unit: "kg",
    image: "/meat-veg-prod/longan.jpeg",
    imageLabel: "Purple-red passion fruits growing on a vine",
    category: "16 / FRUITS",
    name: "Passion Fruit",
    description: "Passion fruit for tangy juices, sauces and desserts.",
    enquiry: "Enquire about passion fruit →",
  },
  {
    id: "pomegranates",
    price: 160,
    unit: "kg",
    image: "/meat-veg-prod/pomegranate.jpeg",
    imageLabel: "Pomegranates growing on trees",
    category: "17 / FRUITS",
    name: "Pomegranates",
    description: "Pomegranates for fruit servings, salads, garnishes and juices.",
    enquiry: "Enquire about pomegranates →",
  },
  {
    id: "grapes",
    price: 120,
    unit: "kg",
    image: "/meat-veg-prod/grapes.jpeg",
    imageLabel: "Green, red and dark grapes in bunches",
    category: "18 / FRUITS",
    name: "Grapes",
    description: "Grapes for snacking, fruit platters and fresh desserts.",
    enquiry: "Enquire about grapes →",
  },
  {
    id: "bananas",
    price: 60,
    unit: "kg",
    image: "/meat-veg-prod/banana.jpeg",
    imageLabel: "Bunches of green and yellow bananas",
    category: "19 / FRUITS",
    name: "Bananas",
    description: "Bananas for everyday fruit servings, smoothies and baking.",
    enquiry: "Enquire about bananas →",
  },
  {
    id: "litchis",
    price: 220,
    unit: "kg",
    image: "/meat-veg-prod/litchi.jpeg",
    imageLabel: "Bunches of red litchis growing on trees",
    category: "20 / FRUITS",
    name: "Litchis",
    description: "Litchis for seasonal fruit platters, desserts and drinks.",
    enquiry: "Enquire about litchis →",
  },
  {
    id: "papayas",
    price: 50,
    unit: "kg",
    image: "/meat-veg-prod/images (4).jpeg",
    imageLabel: "Green and ripening papayas growing on a tree",
    category: "21 / FRUITS",
    name: "Papayas",
    description: "Papayas for fruit bowls, smoothies and kitchen preparation.",
    enquiry: "Enquire about papayas →",
  },
  {
    id: "red-peppers",
    price: 140,
    unit: "kg",
    image: "/meat-veg-prod/capsicum.jpeg",
    imageLabel: "Glossy red peppers packed in a crate",
    category: "22 / VEGETABLES",
    name: "Red Peppers",
    description: "Red peppers for sauces, roasting and savoury kitchen recipes.",
    enquiry: "Enquire about red peppers →",
  },
];

